const css = `:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#edf7ff;background:#07111e;color-scheme:dark}*{box-sizing:border-box}body{margin:0}main{max-width:900px;margin:auto;padding:64px 24px}h1{font-size:clamp(2.4rem,7vw,5rem);line-height:.96;margin:.32em 0}h2{margin-top:2rem}p,li{color:#b9c9db;line-height:1.65}a{color:#67e8f9}.pill{display:inline-block;padding:7px 12px;border:1px solid #6d28d9;border-radius:99px;color:#c4b5fd}.card{padding:22px;margin:20px 0;border:1px solid #233b56;border-radius:18px;background:#0d1c2e}code{color:#a5f3fc}`;
function page(title, body) { return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${css}</style></head><body><main>${body}</main></body></html>`; }

export function landing(origin) {
  return page("One Click for ChatGPT", `<span class="pill">One brief. One Click. A reviewable handoff.</span><h1>Plan once. Build deliberately.</h1><p>One Click turns the minimum website requirements you provide into a structured build brief. This ChatGPT release does not read or save a One Click account, persist the business brief, create a project or deploy a website.</p><div class="card"><strong>MCP endpoint</strong><p><code>${origin}/mcp</code></p><p>Bounded website inputs · review-before-write handoff · privacy-minimised operational analytics</p></div><p><a href="https://oneclickwebsitedesignfactory.com">One Click website</a> · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/support">Support</a> · <a href="https://github.com/AyobamiH/oneclick-chatgpt-plugin">GitHub</a></p>`);
}

export function privacy() {
  return page("Privacy | One Click", `<span class="pill">Privacy</span><h1>Privacy policy</h1><p>Effective 8 September 2026. One Click for ChatGPT is published by AYOBAMI JOHN HAASTRUP.</p><h2>Website brief preparation</h2><p>The plugin processes only the task-specific website fields supplied to its preparation tool. The current tool accepts industry, primary goal and a small set of optional website-specific fields. It does not request full conversation history, inferred location, credentials, private customer records or generic catch-all notes. The MCP service does not persist the business brief or access a One Click website account.</p><h2>External project creation</h2><p>Preparing a One Click brief does not create or deploy a website. If the user separately authorises project creation, ChatGPT may send the reviewed handoff and any user-selected files to the separately installed Lovable service. Lovable processes that data under its own terms and privacy policy.</p><h2>Operational analytics</h2><p>Each tool call may append a minimal operational event containing the tool name, success or error status, rounded latency, release version and coarse client family. Business brief text, prompt text, business names, project IDs, URLs, IP addresses, raw headers and stable user identifiers are not written into this application-level analytics event. These events are used for reliability and aggregate usage measurement and follow the retention controls of the configured Cloudflare analytics service.</p><h2>Contact</h2><p>Use the <a href="/support">support page</a> for privacy questions or requests.</p>`);
}

export function terms() {
  return page("Terms | One Click", `<span class="pill">Terms</span><h1>Terms of service</h1><p>Effective 8 September 2026.</p><p>One Click prepares website drafts and implementation guidance. Generated content is a starting point, not a guarantee or professional advice. Verify business facts and obtain appropriate legal review before publication.</p><p>Do not submit credentials, unrelated private records, full conversation transcripts or content you do not have permission to use. Creating or deploying a Lovable project is a separate action governed by Lovable's terms. This release does not save One Click projects or access One Click accounts.</p><p>The service is provided without warranty. Users remain responsible for reviewing, testing and approving generated websites before deployment.</p>`);
}

export function support() {
  return page("Support | One Click", `<span class="pill">Support</span><h1>One Click support</h1><p>Visit <a href="https://oneclickwebsitedesignfactory.com/support">oneclickwebsitedesignfactory.com/support</a> for product help.</p><p>For plugin bugs, open a minimal, redacted issue at <a href="https://github.com/AyobamiH/oneclick-chatgpt-plugin/issues/new">GitHub Issues</a>. Never include passwords, tokens, private customer data, full chat transcripts or unpublished reference files.</p>`);
}
