import { VERSION } from "./version.js";

export const SUPPORT_EMAIL = "john@tailwaggingwebdesign.com";
export const PRIVACY_EFFECTIVE_DATE = "21 September 2026";
const privacyEmail = `mailto:${SUPPORT_EMAIL}?subject=One%20Click%20privacy%20request`;
const css = `:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#edf7ff;background:#07111e;color-scheme:dark}*{box-sizing:border-box}body{margin:0}main{max-width:1000px;margin:auto;padding:48px 24px 72px}h1{font-size:clamp(2.4rem,7vw,4.4rem);line-height:1.05;margin:.4em 0}h2{margin-top:2.5rem;scroll-margin-top:24px}h3{margin-top:1.8rem}p,li,td,th{line-height:1.65}p,li,td{color:#b9c9db}a{color:#67e8f9;overflow-wrap:anywhere}a:focus-visible{outline:2px solid #67e8f9;outline-offset:4px}.pill{display:inline-block;padding:7px 12px;border:1px solid #6d28d9;border-radius:99px;color:#c4b5fd}.card{padding:22px;margin:24px 0;border:1px solid #233b56;border-radius:18px;background:#0d1c2e}code{color:#a5f3fc;overflow-wrap:anywhere;font-size:.92em}nav{display:flex;gap:12px 24px;flex-wrap:wrap;margin:24px 0}table{width:100%;border-collapse:collapse;margin:20px 0;table-layout:fixed}th,td{text-align:left;vertical-align:top;padding:14px 12px;border-bottom:1px solid #233b56;overflow-wrap:anywhere}th{color:#edf7ff;background:#0d1c2e}th:first-child{width:34%}caption{text-align:left;color:#b9c9db;margin-bottom:12px}footer{margin-top:48px;padding-top:20px;border-top:1px solid #233b56;font-size:.9rem}@media(max-width:560px){main{padding:32px 18px 48px}th,td{padding:12px 7px;font-size:.92rem}th:first-child{width:40%}.card{padding:18px}nav{gap:12px 18px}}`;
function page(title, body) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${css}</style></head><body><main>${body}<footer><nav aria-label="One Click information"><a href="/">One Click</a><a href="/privacy">Privacy policy</a><a href="/terms">Terms</a><a href="/support">Support</a></nav></footer></main></body></html>`;
}

export function landing(origin) {
  return page("One Click for ChatGPT", `<span class="pill">One brief. One Click. A reviewable handoff.</span><h1>Plan once. Build deliberately.</h1><p>One Click turns the minimum website requirements you provide into a structured build brief. This ChatGPT release does not read or save a One Click account, persist the business brief, create a project or deploy a website.</p><div class="card"><strong>MCP endpoint</strong><p><code>${origin}/mcp</code></p><p>Bounded website inputs · review-before-write handoff · minimal operational analytics</p></div><p>Read the <a href="/privacy">privacy policy</a> for the data used, three-month analytics retention and your controls. For help, <a href="/support">contact One Click support</a>.</p><p><a href="https://oneclickwebsitedesignfactory.com">One Click website</a> · <a href="https://github.com/AyobamiH/oneclick-chatgpt-plugin">GitHub</a></p>`);
}

export function privacy() {
  return page("Privacy | One Click", `<span class="pill">Privacy · release ${VERSION}</span>
<h1>Privacy policy</h1>
<p>Effective ${PRIVACY_EFFECTIVE_DATE}. This policy covers the One Click for ChatGPT preparation service and its information pages. The operator and controller is AYOBAMI JOHN HAASTRUP, United Kingdom. Contact: <a href="${privacyEmail}">${SUPPORT_EMAIL}</a>.</p>
<div class="card"><p>One Click uses the website details you choose to provide to prepare a brief and return it to your chat. It does not save that brief in an account or project database. Small operational events are kept for three months. Creating a website through Lovable is a separate action that you review and authorise.</p></div>
<nav aria-label="Privacy sections"><a href="#data">Data and purposes</a><a href="#recipients">Recipients</a><a href="#retention">Retention</a><a href="#controls">Your controls</a><a href="#requests">Privacy requests</a></nav>

<h2 id="data">1. Data we process and why</h2>
<h3>Website requirements and generated output</h3>
<p>The preparation tool receives the specific fields that ChatGPT, Codex or your MCP client sends for your request. These can contain personal data if, for example, you choose a sole trader's name as a business name. The tool requires only an industry and a primary website goal; every other field is optional.</p>
<table><caption>Accepted website fields</caption><thead><tr><th scope="col">Field</th><th scope="col">Purpose and limit</th></tr></thead><tbody>
<tr><th scope="row">Industry<br><code>industry</code></th><td>Required. Business type used to shape the brief; up to 120 characters.</td></tr>
<tr><th scope="row">Primary goal<br><code>primary_goal</code></th><td>Required. The outcome the website should support; up to 240 characters.</td></tr>
<tr><th scope="row">Business name<br><code>business_name</code></th><td>Optional. Names the draft; up to 100 characters. A generic label is used if omitted.</td></tr>
<tr><th scope="row">Brand direction<br><code>brand_vibe</code></th><td>Optional. Describes the desired tone and style; up to 160 characters.</td></tr>
<tr><th scope="row">Headline<br><code>headline</code></th><td>Optional. Supplies headline direction; up to 180 characters.</td></tr>
<tr><th scope="row">Call to action<br><code>call_to_action</code></th><td>Optional. Describes the main visitor action; up to 80 characters.</td></tr>
<tr><th scope="row">Layout<br><code>layout</code></th><td>Optional. Selects a layout from the tool's fixed list.</td></tr>
<tr><th scope="row">Services<br><code>services</code></th><td>Optional. Lists services to include; up to 12 items of 120 characters each.</td></tr>
</tbody></table>
<p>We validate these fields, normalise their text and return a structured brief, a generated build prompt and a reminder to review it before authorising external project creation. The output includes the supplied website details. One Click does not fetch files, browse reference URLs, call an AI model, or contact Lovable while preparing this response.</p>
<p>Do not send passwords, API keys, payment card details, government identifiers, health information, private customer records or unrelated conversation history. There are no fields for files, account credentials, location or full chat transcripts. Unknown fields are rejected. Text fields cannot reliably detect every kind of sensitive information: only include business information needed for the brief.</p>

<h3>Operational events</h3>
<p>To measure reliability and aggregate usage, a tool attempt may record: the event type, a fixed tool label (or <code>unknown_tool</code>), success or error outcome, rounded processing time, numeric response status, release version and a coarse client family (ChatGPT, Codex or other MCP). Cloudflare Analytics Engine also assigns an event timestamp and sampling metadata.</p>
<p>The client family is determined from the User-Agent and Origin headers; the raw values are not saved in the event. We do not put brief content, generated prompts, business names, URLs, IP addresses, raw request headers, error details, arbitrary tool names, account IDs or persistent user identifiers into these events. We do not use them to identify users, profile behaviour, advertise, sell data or train AI models.</p>

<h3>Hosting and support</h3>
<p>Cloudflare processes network information such as IP addresses, request headers, request paths and transport metadata to receive, route and protect HTTPS requests. This processing is distinct from the minimal operational events above. Stored Worker request logs, invocation logs, tracing and log export are disabled for this release; our application does not write request content to console logs.</p>
<p>If you email support, we receive your email address, message, attachments you choose to send and our correspondence. We use these only to answer the request, investigate a reported problem or handle your privacy rights. Please send a short description and a redacted example; a full chat transcript is not needed.</p>

<h2 id="recipients">2. Who receives the data</h2>
<ul>
<li><strong>Cloudflare:</strong> hosts the preparation service and stores the minimal Analytics Engine events on our behalf. Its separate processing for network security and service administration is described in <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare's privacy policy</a>.</li>
<li><strong>OpenAI or your chosen MCP client:</strong> sends the selected inputs and receives the brief and build prompt. Chat history, client-side copies and OpenAI's use or retention of that data are controlled by that service and your settings, not by One Click. See <a href="https://openai.com/policies/privacy-policy/">OpenAI's privacy policy</a>.</li>
<li><strong>Lovable, only after a separate action:</strong> if you authorise ChatGPT to create a project using the separately installed Lovable service, ChatGPT may send the reviewed handoff and any files you separately select to Lovable. One Click's preparation tool does not perform that transfer. See <a href="https://lovable.dev/privacy">Lovable's privacy policy</a>.</li>
<li><strong>Support recipients:</strong> the operator and email service providers handle support correspondence. We do not ask you to post privacy requests on public GitHub issues.</li>
</ul>
<p>These providers may process data outside the UK, including in the United States. Applicable provider data-processing terms and transfer safeguards govern processing they perform for us. Contact us for information about the safeguards applicable to your request. Data you send through a separate OpenAI, MCP client or Lovable account is also subject to that provider's terms.</p>

<h2 id="retention">3. How long data is kept</h2>
<table><caption>Retention by data category</caption><thead><tr><th scope="col">Data</th><th scope="col">Retention and deletion</th></tr></thead><tbody>
<tr><th scope="row">Website inputs and generated brief</th><td>Processed in memory for the request and returned to the calling client. One Click does not persist them, create saved projects, or maintain a brief history or backup to retrieve or delete later. The service does not promise deletion of copies kept by your client.</td></tr>
<tr><th scope="row">Operational analytics</th><td>Cloudflare Analytics Engine retains events for <strong>three months</strong>, after which they expire. We do not export them to a separate long-term store. This is the provider's documented period, not a claim that three months always equals 90 days. See <a href="https://developers.cloudflare.com/analytics/analytics-engine/limits/#data-retention">Analytics Engine retention</a>.</td></tr>
<tr><th scope="row">Worker logs from earlier releases</th><td>New stored Worker logs are disabled in this release. Previously collected logs may remain in Cloudflare for up to <strong>seven days from collection</strong> before expiry. Disabling logging does not erase existing logs. See <a href="https://developers.cloudflare.com/workers/observability/logs/workers-logs/">Workers Logs retention</a>.</td></tr>
<tr><th scope="row">Cloudflare network/service records</th><td>Cloudflare controls records it processes for its own network security and service administration. Its privacy policy describes retention according to the purpose, security needs and legal requirements. The three-month event limit above does not describe all provider-held records.</td></tr>
<tr><th scope="row">Support correspondence</th><td>Kept while resolving your request and for up to <strong>90 days after closure</strong>, then deleted from our active support mailbox. If a specific legal duty or unresolved dispute requires longer retention, we limit the retained material to that purpose, explain the reason when applicable, and delete it when that need ends. Email providers may retain residual backups under their own policies.</td></tr>
<tr><th scope="row">ChatGPT, other clients and Lovable</th><td>The relevant provider's retention rules and your account settings apply to its copies. Deleting or disconnecting One Click does not automatically delete a chat or a separately created Lovable project.</td></tr>
</tbody></table>

<h2 id="controls">4. Your choices and controls</h2>
<ul>
<li>Provide only the required industry and goal, use a generic business label and omit optional details. Review the fields that your client proposes to send and decline the tool call if you do not want them processed. Without the two required fields, One Click cannot prepare the brief.</li>
<li>Review and edit the returned handoff before any external project creation. You can stop after preparation and decline the separate Lovable action.</li>
<li>Disconnect or stop using One Click in your client to prevent future calls. Use that client's chat deletion and privacy settings for copies in the conversation.</li>
<li>Direct MCP clients can suppress the operational event for an individual request by sending <code>DNT: 1</code> or <code>Sec-GPC: 1</code>. The brief still works. This choice is read for that request only and creates no cookie or stored identifier. ChatGPT may not expose custom request headers; One Click does not claim that an in-chat analytics toggle exists.</li>
<li>Ask us to access, correct or delete support correspondence, or to restrict processing where applicable. Operational events contain no persistent user identifier, so we cannot reliably find an individual user's events; we do not collect extra identity data just to link them. They expire after three months.</li>
</ul>
<p>These information pages set no cookies, use no browser storage and include no third-party tracking scripts. This statement covers this plugin service, not the separate One Click website or other linked services.</p>

<h2 id="requests">5. Privacy requests and rights</h2>
<p>Email <a href="${privacyEmail}">${SUPPORT_EMAIL}</a> with the subject <strong>One Click privacy request</strong>. Describe what you want us to do and provide only enough information to locate the relevant correspondence. We may ask for proportionate verification before disclosing personal information; do not send identity documents or secrets with your first message.</p>
<p>Where UK data protection law applies, we process information necessary to provide the service you request (performance of our service contract), rely on legitimate interests for proportionate reliability monitoring and ordinary support, and comply with legal obligations when handling applicable rights requests. We do not make automated decisions that have legal or similarly significant effects on you.</p>
<p>You may have rights to access, correction, erasure, restriction and portability, depending on the circumstances. <strong>You can object to processing based on legitimate interests</strong> by emailing the privacy contact. We consider requests individually and explain any applicable limits, including data we do not hold. You may also complain to the <a href="https://ico.org.uk/make-a-complaint/">UK Information Commissioner's Office</a> or your local data protection authority.</p>
<h2>6. Changes to this policy</h2>
<p>We update this page when the service's data handling changes and show the effective date above. Any future account storage, new recipient or expanded tool input requires a fresh disclosure before it is introduced.</p>`);
}

export function terms() {
  return page("Terms | One Click", `<span class="pill">Terms</span><h1>Terms of service</h1><p>Effective ${PRIVACY_EFFECTIVE_DATE}. One Click for ChatGPT is operated by AYOBAMI JOHN HAASTRUP.</p><p>One Click prepares website drafts and implementation guidance. Generated content is a starting point, not a guarantee or professional advice. Verify business facts before publication.</p><p>Do not submit credentials, unrelated private records, full conversation transcripts or content you do not have permission to use. Creating or deploying a Lovable project is a separate action governed by Lovable's terms. This release does not save One Click projects or access One Click accounts.</p><p>Data handling, retention and available controls are described in the <a href="/privacy">privacy policy</a>. The service is provided without warranty. Users remain responsible for reviewing, testing and approving generated websites before deployment.</p><p>For help or privacy requests, use the <a href="/support">support page</a>.</p>`);
}

export function support() {
  return page("Support | One Click", `<span class="pill">Support</span><h1>Contact One Click</h1><p>For help with this ChatGPT preparation service, email <a href="mailto:${SUPPORT_EMAIL}?subject=One%20Click%20plugin%20support">${SUPPORT_EMAIL}</a>. The operator is AYOBAMI JOHN HAASTRUP.</p><div class="card"><h2 id="privacy-requests">Private privacy requests</h2><p><a href="${privacyEmail}">Email a One Click privacy request</a> to ask about access, correction, deletion, restriction or objection. Use the subject <strong>One Click privacy request</strong> and describe the relevant correspondence or concern.</p><p>Do not put a privacy request, credentials, identity documents, private customer data, full chat transcripts or unpublished files in a public GitHub issue. Send only the minimum information needed to help.</p></div><p>One Click does not save website briefs or account/project histories. Support correspondence is retained while your request is handled and for up to 90 days after closure, subject to the limited exceptions explained in the <a href="/privacy#retention">privacy policy</a>.</p><p>For a non-sensitive software bug, you can also open a minimal, redacted <a href="https://github.com/AyobamiH/oneclick-chatgpt-plugin/issues/new">GitHub issue</a>. Public issues are visible to other people and subject to GitHub's retention and deletion controls.</p>`);
}
