import {App} from "@modelcontextprotocol/ext-apps";
import {OpenAIExtensions} from "@openai/mcp-extensions/app";
const app=new App({name:"One Click workspace",version:"1.1.0"},{});
const extensions=new OpenAIExtensions(app);
const byId=id=>document.getElementById(id);
const serviceConfiguration=JSON.parse(document.getElementById("service-configuration")?.textContent??"{}");
if(serviceConfiguration.reviewMode){const notice=document.createElement("p");notice.className="status";notice.textContent="Review release: synthetic accounts only. Customer sign-up and payments are disabled.";document.querySelector("header").prepend(notice);}
let access=null,result=null,busy=false,hostReady=false,fullReady=serviceConfiguration.fullModeReady===true,selectedProject=null,knowledgeVersion=0,expiryTimer=null;
function controls(){document.querySelectorAll("button").forEach(b=>b.disabled=busy||!hostReady);byId("connect").disabled=busy||!hostReady||!fullReady;}
function status(text){byId("status").textContent=text;}
function theme(){const context=app.getHostContext();for(const [key,value] of Object.entries(context?.styles?.variables??{}))if(typeof value==="string")document.documentElement.style.setProperty(key,value);const insets=context?.safeAreaInsets;if(insets)document.body.style.padding=`${Math.max(16,insets.top??0)}px ${Math.max(16,insets.right??0)}px ${Math.max(16,insets.bottom??0)}px ${Math.max(16,insets.left??0)}px`;}
function refreshExpiredAccess(){if(busy){expiryTimer=setTimeout(refreshExpiredAccess,250);return;}void action(async()=>renderAccess(await call("oneclick_get_full_access")));}
function renderAccess(a){if(expiryTimer!==null)clearTimeout(expiryTimer);access=a;if(a?.state==="trial_active"){const remaining=Date.parse(a.trial.expiresAt)-Date.now();expiryTimer=setTimeout(refreshExpiredAccess,Math.max(20,Math.min(remaining+20,2147483647)));}const full=Boolean(a?.fullMode);byId("trial-intro").hidden=a?.state==="paid";byId("trial-disclosure").hidden=a?.state==="paid";byId("full-fields").hidden=!full;byId("goal").maxLength=full?200:240;byId("save-project").hidden=!full||!result;byId("trial-consent").hidden=!a?.trialAvailable;byId("checkout").hidden=!a||a.state!=="trial_expired"||!a.offer?.continuation?.available;byId("connect").hidden=Boolean(a);byId("prepare").textContent=full?"Prepare Full Mode brief":"Prepare website brief";byId("availability").textContent=a?.state==="trial_active"?`Full Mode trial ends ${new Date(a.trial.expiresAt).toLocaleString()}. ${a.ticketsRemaining} support tickets remain.`:a?.state==="paid"?`Lifetime Full Mode access. ${a.ticketsRemaining} support tickets remain.`:a?.state==="trial_expired"?"Your trial has ended. Your saved work stays in your account; choose whether to continue.":a?.trialAvailable?"Start the trial when you are ready. Your 72 hours begin after you confirm.":"Full Mode trial activation is not available yet.";}
async function call(name,args={}){const r=await app.callServerTool({name,arguments:args});if(r.isError)throw Error(r.structuredContent?.message??"The request could not be completed. Please try again.");return r.structuredContent;}
async function action(fn){if(busy)return;busy=true;controls();try{await fn();}catch(e){status(e.message||"The request could not be completed. Please try again.");}finally{busy=false;controls();}}
for(const button of document.querySelectorAll("[data-view]"))button.addEventListener("click",()=>{document.querySelectorAll(".view").forEach(v=>v.hidden=v.id!==button.dataset.view);document.querySelectorAll("[data-view]").forEach(b=>b.setAttribute("aria-selected",String(b===button)));});
byId("connect").addEventListener("click",()=>action(async()=>{if(!fullReady)throw Error("Full Mode connection is not available in this preview yet.");renderAccess(await call("oneclick_get_full_access"));status("One Click account connected.");}));
byId("start-trial").addEventListener("click",()=>action(async()=>{if(!byId("accept-trial").checked)throw Error("Please confirm the trial duration and optional continuation price.");renderAccess(await call("oneclick_start_full_trial",{accept_trial_terms:true,policy_version:"oneclick.full-trial.v1"}));status("Your 3-day Full Mode trial has started.");}));
byId("brief-form").addEventListener("submit",event=>{event.preventDefault();action(async()=>{const form=Object.fromEntries(new FormData(event.currentTarget));const args={industry:form.industry,primary_goal:form.primary_goal,...(form.business_name?{business_name:form.business_name}:{}),...(form.brand_vibe?{brand_vibe:form.brand_vibe}:{}),...(form.services.trim()?{services:form.services.split("\n").map(s=>s.trim()).filter(Boolean)}:{})};if(access?.fullMode){if(!form.business_name.trim()||!form.location.trim()||!form.brand_vibe.trim())throw Error("Full Mode needs a business name, location and brand feel supplied by you.");Object.assign(args,{location:form.location,target_audience:form.target_audience,extra_notes:form.extra_notes,layout:form.layout,...(form.preset?{preset:form.preset}:{}),...(form.reference_url.trim()?{reference_url:form.reference_url.trim()}:{}),...(form.headline.trim()?{headline:form.headline.trim()}:{}),...(form.call_to_action.trim()?{call_to_action:form.call_to_action.trim()}:{}),image_urls:form.image_urls.split("\n").map(v=>v.trim()).filter(Boolean)});}result=await call(access?.fullMode?"oneclick_prepare_full_draft":"oneclick_prepare_basic_draft",args);byId("result").textContent=result.lovable?.initial_message+(result.lovable?.project_knowledge?"\n\nPROJECT KNOWLEDGE DRAFT\n"+result.lovable.project_knowledge:"");byId("result").hidden=false;byId("result-empty").hidden=true;byId("add-to-chat").hidden=false;byId("save-project").hidden=!access?.fullMode;status("Your brief is ready to review.");});});
byId("add-to-chat").addEventListener("click",()=>action(async()=>{if(!result)return;if(extensions.modelContext)await extensions.modelContext.update({content:[{type:"text",text:byId("result").textContent}],structuredContent:{tier:result.tier,reviewed:true}});else await app.updateModelContext({content:[{type:"text",text:byId("result").textContent}]});status("Reviewed brief added to this conversation.");}));
byId("save-project").addEventListener("click",()=>action(async()=>{if(!result?.projectInput)throw Error("Prepare a Full Mode brief before saving.");const saved=await call("oneclick_save_project",{project:result.projectInput,request_key:crypto.randomUUID()});status("Project saved to your One Click account.");}));
byId("checkout").addEventListener("click",()=>action(async()=>{const checkout=await call("oneclick_create_checkout",{request_key:crypto.randomUUID()});const u=new URL(checkout.url);if(u.protocol!=="https:"||u.hostname!=="checkout.stripe.com"||u.username||u.password||u.port)throw Error("The payment link could not be verified.");const r=await app.openLink({url:u.href});if(r.isError)throw Error("The payment page could not be opened.");}));
byId("load-projects").addEventListener("click",()=>action(async()=>{const {items}=await call("oneclick_list_projects");const container=byId("project-results");container.replaceChildren();if(!items.length)container.textContent="You have no saved projects yet.";for(const project of items){const row=document.createElement("div");row.className="actions";const button=document.createElement("button");button.textContent=project.business_name;button.addEventListener("click",()=>action(async()=>{selectedProject=project;byId("project-title").textContent=project.business_name;const {items}=await call("oneclick_get_knowledge_base",{project_id:project.id});knowledgeVersion=items[0]?.version??0;byId("knowledge-content").value=items[0]?.content??(`# Project knowledge: ${project.business_name}\n\nBusiness type: ${project.business_type}\nLocation: ${project.location}\nGoal: ${project.primary_goal}\nBrand: ${project.brand_vibe}\n\nOwner notes\n${project.extra_notes??"Add verified content and contact details."}\n\nDeveloper insights\n${project.build_insights??"Review and verify implementation requirements before launch."}`);byId("project-detail").hidden=false;status("Project opened.");}));row.append(button);container.append(row);}}));
byId("load-tickets").addEventListener("click",()=>action(async()=>{const {items}=await call("oneclick_list_support_tickets");const container=byId("ticket-results");container.replaceChildren();if(!items.length)container.textContent="You have no support requests yet.";for(const ticket of items){const row=document.createElement("p");row.textContent=ticket.subject+" — "+ticket.status;container.append(row);}}));
byId("ticket-form").addEventListener("submit",event=>{event.preventDefault();action(async()=>{const input=Object.fromEntries(new FormData(event.currentTarget));await call("oneclick_create_support_ticket",{...input,request_key:crypto.randomUUID()});renderAccess(await call("oneclick_get_full_access"));status("Support ticket submitted.");});});
app.addEventListener("hostcontextchanged",theme);
app.addEventListener("toolresult",params=>{if(params.structuredContent?.workspace){fullReady=Boolean(params.structuredContent.fullModeReady);controls();status(fullReady?"Prepare a brief or connect your One Click account for Full Mode.":"Website briefs are available. Full Mode is awaiting service activation.");}});
controls();
void app.connect().then(()=>{hostReady=true;theme();controls();status(fullReady?"Prepare a brief or connect your One Click account for Full Mode.":"Website briefs are available. Full Mode is awaiting service activation.");}).catch(()=>status("Open this workspace inside the One Click plugin in ChatGPT."));

byId("save-knowledge").addEventListener("click",()=>action(async()=>{if(!selectedProject)return;const content=byId("knowledge-content").value;if(!content.trim())throw Error("Add project knowledge before saving.");const saved=await call("oneclick_save_knowledge_base",{project_id:selectedProject.id,id:crypto.randomUUID(),content,expected_version:knowledgeVersion});knowledgeVersion=saved.version;status("Knowledge base saved.");}));
byId("load-handoff").addEventListener("click",()=>action(async()=>{if(!selectedProject)return;const handoff=await call("oneclick_get_handoff",{project_id:selectedProject.id});byId("project-output").textContent=handoff.sections.map(([title,text])=>title+"\n"+text).join("\n\n")+"\n\nLaunch checklist\n"+handoff.checklist.join("\n");byId("project-output").hidden=false;status("Developer handoff pack prepared.");}));
byId("create-branding").addEventListener("click",()=>action(async()=>{if(!selectedProject)return;const kit=await call("oneclick_create_brand_kit",{project_id:selectedProject.id,id:crypto.randomUUID(),palette:byId("palette").value});const preview=byId("brand-preview");preview.replaceChildren();const logo=document.createElement("div");logo.textContent=kit.monogram;logo.style.cssText="width:112px;height:112px;border-radius:24px;display:grid;place-items:center;font-size:36px;font-weight:700;color:#fff;margin-top:16px";if(/^#[a-f0-9]{6}$/i.test(kit.palette.primary))logo.style.background=kit.palette.primary;preview.append(logo);const description=document.createElement("p");description.textContent="Colours: "+Object.entries(kit.palette).map(([name,value])=>name+" "+value).join(", ")+". Headings: "+kit.typography.heading+". Body: "+kit.typography.body+".";preview.append(description);preview.hidden=false;byId("project-output").textContent=kit.guidelines+"\n\nEditable SVG source\n"+kit.logoSvg;byId("project-output").hidden=false;status("Editable brand kit saved to this project.");}));
